--- ./Makefile	2010-04-14 10:08:02.000000000 +0400
+++ ./Makefile	2010-04-28 13:02:42.481512199 +0400
@@ -296 +296 @@
-	test -z "$(pkgconfigdir)" || $(MKDIR_P) "$(DESTDIR)$(pkgconfigdir)"
+	test -z "$(DESTDIR)$(pkgconfigdir)" || $(MKDIR_P) "$(DESTDIR)$(pkgconfigdir)"
